# Generated by Django 4.2.7 on 2023-12-02 00:46

from django.db import migrations, models
import django.db.models.deletion
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('driveyou', '0003_searchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='duration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='end_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='end_lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='start_lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='start_lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='user_travel_time',
            field=models.DateTimeField(validators=[validators.validate_date_travel_date]),
        ),
        migrations.CreateModel(
            name='DriverPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_radius', models.PositiveIntegerField(default=10)),
                ('travel_distance', models.PositiveIntegerField(default=100)),
                ('overnight_trip', models.BooleanField(default=True)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('music_preference', models.CharField(choices=[('classical', 'Classical'), ('rock', 'Rock'), ('pop', 'Pop'), ('none', 'None')], default='none', max_length=50)),
                ('smoking_preference', models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed'), ('neutral', 'Neutral')], default='neutral', max_length=50)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_preferences', to='driveyou.driver')),
            ],
        ),
    ]
